- src/DropzoneArea.js
- src/PreviewList.js
It can be difficult to discern between non-image files due to the generic preview image used for these files (1st screenshot). This PR adds an option to show the file name beneath the preview image (2nd and 3rd screenshots). Note that the option defaults to false to maintain consistent functionality with previous versions.
> Add option to show file name in preview

- src/index.d.ts
Added DropzoneArea's showFileNamesInPreview to the type definitions. resovles issue #28 and is related to #26.
> Added DropzoneArea's showFileNamesInPreview to the type definitions

- src/DropzoneArea.js
Fixes an issue where dropzoneText does not get set by props.
Resolves: https://github.com/Yuvaleros/material-ui-dropzone/issues/42
> Fix dropzoneText prop to properly set state

- README.md
I added the showFileNames property to the list of DropzoneArea Component Properties. I spent more time than I'd like to admit trying to figure out why showFileNamesInPreview wasn't working... Hopefully this helps others in the future.
> added showFileNames to README

- src/SnackbarContentWrapper.js
this is to remove the warning:
Warning: Material-UI: theme.spacing.unit usage has been deprecated.
It will be removed in v5.
You can replace `theme.spacing.unit * y` with `theme.spacing(y)`.
theme.spacing.unit is deprecated and will be removed around January 2020
> Remove material-ui deprecated theme.spacing.unit

- src/DropzoneArea.js
currently anything overridden in user dropzoneClass that is also in the coded dropzoneclass does not apply e.g. min-height
> User dropzoneClass should take precedence

- src/index.d.ts
After some fumbling around I figured out that my editor was complaining about the `initialProps` not being there because the typescript definition file was not updated with it. Hope this helps.
> Allow initialFiles prop when using typescript

- README.md
This PR is to fix typos from boolean & string to Boolean and String respectively.
> Typo fixes for README.md file.

- dist/index.d.ts
I was waiting for the recent PR to update the typescript type definitions, but I noticed that they weren't actually updated in the dist folder.
The new types aren't available via the npm distribution because of this.
This is simply copying the updated types into the correct folder so they can actually be used.
> Update types in the dist folder for npm

- src/helpers/helpers.js
Better to avoid checking by extension and rely on mime types.
> Fix isImage helper function

- src/DropzoneDialog.js
dialogProps is an object to allow customize classNames and allow draggable pattern like so:
[https://material-ui.com/components/dialogs/#draggable-dialog](url)
> Add dialogProps prop to customize DropzoneDialog appearance.

- example/yarn.lock
- package.json
- yarn.lock
This PR upgrade `react-dropzone` to version `10.2.1` and updates the implementation to match the new component usage.
This PR introduce a breaking change since `react-dropzone` v10+ dropped support for `react` versions older than v`16.8` (see release notes [here](https://github.com/react-dropzone/react-dropzone/releases/tag/v10.0.0)).
Also this PR drops support for `material-ui` version `3`.
I'd suggest this to be a `major` version bump for `material-ui-dropzone` (so bump to version `3.0.0`) and, if support for older versions of `react` and `material-ui` is still required, you can think to keep a `v2` branch with the previous implementation so that users of this library can decide to use `v2.x` or `v3.x` based on their needs whilst keep them updated independently (I think that many …
> [BREAKING] Upgrade react-dropzone to version 10

- .github/workflows/build.yml
This PR adds a Github Action to rebuild the package to the `dist` folder when pushing to `master` or to `v2.x` branches, this will avoid having to rebuild and pushing manually each time a change gets merged into one of the 2 main branches.
> Add GH Action to Rebuild 'dist' on push

- .github/workflows/build.yml
This PR adds a Github Action to rebuild the package to the dist folder when pushing to master or to v2.x branches, this will avoid having to rebuild and pushing manually each time a change gets merged into one of the 2 main branches.
> Add GH Action to Rebuild 'dist' on push (v2.x branch)

- src/components/DropzoneArea.js
This PR adds the new `disableRejectionFeedback` prop to `DropzoneArea` component to allow disabling the 'red-stripes' validation feedback when `react-dropzone` detects rejected files.
> Add prop to disable 'red-stripes' feedback effect (v2 backport)

- src/components/DropzoneArea.js
This PR adds the new `disableRejectionFeedback` prop to `DropzoneArea` component to allow disabling the 'red-stripes' validation feedback when `react-dropzone` detects rejected files.
> Add prop to disable 'red-stripes' feedback effect

- .eslintrc.json
- src/components/DropzoneArea.js
- src/index.d.ts
This PR adds new customisation props to the `DropzoneArea` component.
This also updates the ESLint config to avoid throwing errors for long JSDoc comments.
This changes are based on the `master` (v3.0) branch and I'd say they can be released as `v3.1`, as soon as approved I'll backport them to the `v2.x` branch.
> Add more customization props

- src/helpers.js
This PR removes the filename handling from `createFileFromUrl` helper method to avoid causing issues such as duplicated extensions.
- Fixes #135 
Bug fix (non-breaking change which fixes an issue)
> Avoid appending extension if present when loading external files (v2 backport)

- src/helpers.js
This PR removes the filename handling from `createFileFromUrl` helper method to avoid causing issues such as duplicated extensions.
- Fixes #135 
Bug fix (non-breaking change which fixes an issue)
> Avoid appending extension if present when loading external files

- src/components/DropzoneArea.js
- src/components/DropzoneArea.md
- src/components/PreviewList.js
This is a backport of a PR already implemented implemented, but here's the description of that PR
I have created a new prop `getPreviewIcon` which allows you to pass your own function which determines which Preview Icon should be displayed for selected file.
I also added an example in the markdown as this was useful for testing, and thought it would also be useful so that people can see how to use the prop and a possible use case for it
- Fixes #149 
- Browser:
> Preview icon backport

- src/components/DropzoneArea.js
- src/components/DropzoneArea.md
- src/components/PreviewList.js
I have created a new prop `getPreviewIcon` which allows you to pass your own function which determines which Preview Icon should be displayed for selected file.
I also added an example in the markdown as this was useful for testing, and thought it would also be useful so that people can see how to use the prop and a possible use case for it
- Browser:
Windows 10, Chrome Browser
There is a linting error, not sure how to get around this, any ideas?
There appears to be no testing framework in place
n/a see above
n/a
> :sparkles: Add 'getPreviewIcon' to DropzoneArea

- docs/theming.md
- src/components/DropzoneArea.js
- src/components/DropzoneArea.md
- src/components/PreviewList.js
- src/components/SnackbarContentWrapper.js
- styleguide.config.js
This PR adds support for MUI Theme styling and related docs.
- Closes #73 
- Closes #80
- Closes #125
- Closes #146
> Add support for style with MUI Theme

- docs/theming.md
- src/components/DropzoneArea.js
- src/components/DropzoneArea.md
- src/components/PreviewList.js
- src/components/SnackbarContentWrapper.js
- styleguide.config.js
This PR adds support for MUI Theme styling and related docs.
- Closes #73 
- Closes #80
- Closes #125
- Closes #146
> Add support for style with MUI Theme (v2 backport)

- src/components/DropzoneArea.js
- src/index.d.ts
This PR fixes some issues caused after the implementation of `getPreviewIcon` prop. 
- Fixes #159 
- Fixes #161 
> getPreviewIcon fixes

- src/components/DropzoneArea.js
- src/index.d.ts
This PR fixes some issues caused after the implementation of getPreviewIcon prop.
- Fixes #159 
- Fixes #161 
> getPreviewIcon fixes (v2 backport)

- src/components/DropzoneArea.js
- src/components/DropzoneAreaBase.js
- src/components/DropzoneAreaBase.md
- src/components/DropzoneDialog.js
- src/components/DropzoneDialogBase.js
- src/components/DropzoneDialogBase.md
- src/index.js
This PR introduces 2 new components (`DropzoneAreaBase` and `DropzoneDialogBase`) which are the new 'stateless' base for `DropzoneArea` and `DropzoneDialog` (which are now simple wrapper to add state).
The 2 base components are exported to allow 'controlled' usages as previously requested.
- Fixes #75 
- Fixes #167 
> Add controlled components

- src/components/PreviewList.js
Show the "remove image"-button when it has keyboard focus.
- Fixes #190 
1. Run `yarn docs:dev`.
1. Open the link listed in the console (`localhost:6060`).
1. Upload a file in one of the dropzones.
1. Press `tab` on the keyboard.
- Browser: FireFox 76.0
> Show remove buttons when they have focus.

- src/components/DropzoneArea.md
- src/components/DropzoneAreaBase.js
- src/components/DropzoneDialog.md
- src/components/PreviewList.js
- src/index.d.ts
* Changed the PreviewList to use the Material UI GridList and GridListTile
* Made the Drop files message absolute postitioned so that the previews go over the top of it
* Added a function prop to calculate the number of columns for the GridList
* Added some examples to docs for better development and showcasing the capabilities of what I did
* Ensured the component looks nicer by default and is more responsive by default 
* All the new MaterialUI components can have props passed to them which are spread
* Deprication of the below in favour of 'previewType' which can be 'inside' (default), 'below' or 'none'
*   showFileNamesInPreview, (this one was pointless anyway as we already have showFileNames)
*   showPreviews,
*   showPreviewsInDropzone,
- Fixes #166 
- Breaking change (fix or …
> Improve preview 166 tidy

- src/components/DropzoneArea.md
- src/components/PreviewList.js
Before this PR `previewGridProps` and `previewGridClasses` had no effect if we switched to `useChipsForPreview` and all the chips got stacked one below the other because of the use of a simple div.
Using the already well established **previewGrid** props allow for much more chip customizations.
Chips are now displayed inline by default but thanks to the `previewGridProps` this can be changed at any time
I've tested it personally in one of my projects
- Browser: Chrome
> Make previewChips use the grid system as well

- src/components/DropzoneAreaBase.js
`material-ui/core` uses `justify` prop instead of `justifyContent`. The component Grid inside `DropzoneAreaBase` uses `justifyContent`
Thus resulting in this warning
```javascript
Warning: React does not recognize the `justifyContent` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `justifycontent` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
in div (created by ForwardRef(Grid))
in ForwardRef(Grid) (created by WithStyles(ForwardRef(Grid)))
in WithStyles(ForwardRef(Grid)) (created by Dropzone)
in div (created by Dropzone)
in Dropzone (created by DropzoneAreaBase)
in DropzoneAreaBase (created by WithStyles(DropzoneAreaBase))
in WithStyles(DropzoneAreaBase) (created by …
```
>  🐛 Use `justify` prop instead of `justifyContent`  in the material-ui Grid component   for v4.x 

- src/components/DropzoneArea.js
- src/components/DropzoneDialog.js
Avoid issues when using this module components with `NextJS` where `File` object is not available.
- Fixes #208 
- Browser: Safari 13.1.1
> Fix issues when using module components with 'NextJS'

- src/components/SnackbarContentWrapper.js
Hi, guys! 
Before: 
After:
Please note on close icon
- Browser: chrome 84.0.4147.89
> :lipstick: Snackbar icons margins

- src/components/DropzoneAreaBase.js
This PR changes the default `acceptedFiles` default prop to allow dropping all file types.
- Fixes #214 
> ✨ Allow all filetypes by default

- src/components/DropzoneAreaBase.js
- src/components/DropzoneAreaBase.md
- src/index.d.ts
This PR adds a new `Icon` prop that allow passing a custom icon to be displayed inside the dropzone area.
- Fixes #48 
- Browser: Edge 84
> :sparkles: Custom dropzone icon

- src/components/DropzoneAreaBase.js
This PR fixes the way props are passed to the `react-dropzone` components.
- Fixes #235 
- Browser: Edge 84
> Fix react-dropzone props

- src/helpers.js
`convertBytesToMbsOrKbs` was using the decimal system to convert bytes to megabytes and kilobytes. I switched to binary system to match the actual file's size verification.
- Browser: Firefox 80.0.1
> 🐛 Use binary system to convert bytes to kbs and mbs

- src/index.d.ts
disableRejectionFeedback doesn't currently exist in the DropzoneAreaBaseProps type. This causes an error when using Typescript. 
- Related to #141 
- Tested by launching the interactive docs by running yarn docs:dev and setting the disableRejectionFeedback prop in DropzoneAreaBase components.
- Made sure yarn build works.
- Browser: Chrome Version 85.0.4183.102 (Official Build) (64-bit)
> 🐛 Add disableRejectionFeedback to DropzoneAreaBaseProps type

- src/components/DropzoneDialogBase.js
- src/components/DropzoneDialogBase.md
- src/index.d.ts
* Adding the ability to customise the dialog title with JSX, rather than it just being a string.
- Browser: Chrome Version 84.0.4147.105
> Updating dialogTitle prop to be a string or element

- src/index.d.ts
Current implementation allows setting prop `Icon={<MyIcon />}` instead of `Icon={MyIcon}` causing the build to fail.
```
import { DropzoneArea } from 'material-ui-dropzone';
import ArrowForwardIcon from '@material-ui/icons/ArrowForward';
...
<DropzoneArea
Icon={ArrowForwardIcon}  <-- Compile error
/>
```
> Fixes typings

- src/components/DropzoneArea.js
Pass the index of the deleted file object to DropZoneArea's `onDelete` prop. 
I use this module in my project where I pass a list of URLs as `initialImages`. However, once the images are loaded to DropZoneArea, the original URL is no longer known. When an image passed as an initial image is deleted, the parent component which uses `DropZoneArea` cannot discern which image was deleted because of the lack of original URL or index of the deleted image passed to `onDelete` function.
This PR exposes the deleted file index to a parent component, so that a parent component can discern the exact image which was deleted.
```js
const onDelete = (deletedFile, deletedFileIndex) => {
console.log(deletedFileIndex)
}
<DropZoneArea 
onDelete={onDelete} …
```
> :bug: Pass deleted file index to onDelete in DropZoneArea
